[package]
name = "subversion"
version = "0.0.4"
edition = "2021"
authors = ["Jelmer Vernooĳ <jelmer@apache.org>"]
repository = "https://github.com/jelmer/subversion-rs.git"
homepage = "https://github.com/jelmer/subversion-rs"
license = "Apache-2.0"
description = "Rust bindings for Subversion"
documentation = "https://docs.rs/subversion"

[lib]
doctest = false

[dependencies]
apr = { version = "0.1" }
#apr = { path = "../apr-rs" }
ctor = "0.2.8"
lazy_static = "1.4.0"
pyo3 = { version = ">=0.19", optional = true }
url = { version = "2.5.0", optional = true }

[features]
pyo3 = ["dep:pyo3"]
url = ["dep:url"]

[build-dependencies]
bindgen = "0.69"
system-deps = "7.0"

[dev-dependencies]
tempfile = "3.10.1"

[package.metadata.system-deps]
libsvn_client = ">=1.14"
libsvn_subr = ">=1.14"
libsvn_repos = ">=1.14"
libsvn_fs = ">=1.14"
libsvn_wc = ">=1.14"
libsvn_ra = ">=1.14"
