[package]
name = "subversion"
version = "0.0.2"
edition = "2021"
authors = ["Jelmer Vernooĳ <jelmer@apache.org>"]
repository = "https://github.com/jelmer/subversion-rs.git"
homepage = "https://github.com/jelmer/subversion-rs"
license = "Apache-2.0"
description = "Rust bindings for Subversion"

[lib]
doctest = false

[dependencies]
apr = { version = "0.1.1" }
ctor = "0.2.5"
lazy_static = "1.4.0"

[build-dependencies]
bindgen = "0.68"
pkg-config = "0.3"
system-deps = "6.2"

[package.metadata.system-deps]
libsvn_client = "*"
libsvn_subr = "*"
