[package]
name = "subversion"
version = "0.0.3"
edition = "2021"
authors = ["Jelmer Vernooĳ <jelmer@apache.org>"]
repository = "https://github.com/jelmer/subversion-rs.git"
homepage = "https://github.com/jelmer/subversion-rs"
license = "Apache-2.0"
description = "Rust bindings for Subversion"

[lib]
doctest = false

[dependencies]
apr = { version = "0.1" }
#apr = { path = "../apr-rs" }
ctor = "0.2.5"
lazy_static = "1.4.0"
pyo3 = { version = ">=0.19", optional = true }
url = { version = "2.2.0", optional = true }

[features]
pyo3 = ["dep:pyo3"]
url = ["dep:url"]

[build-dependencies]
bindgen = "0.68"
system-deps = "6.2"

[dev-dependencies]
tempfile = "3.8.1"

[package.metadata.system-deps]
libsvn_client = ""
libsvn_subr = ""
libsvn_repos = ""
libsvn_fs = ""
libsvn_wc = ""
libsvn_ra = ""
